{% set version = "0.2.2" %}

package:
  name: intake-stac
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/i/intake-stac/intake_stac-{{ version }}.tar.gz
  sha256: 459fc585cafda0509b696bec59cc089d7868d6670f9345a804b3613aebd84c61

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3
    - intake-xarray
    - sat-stac

test:
  imports:
    - intake_stac
    - intake_stac.catalog

about:
  home: https://github.com/pangeo-data/intake-stac
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Intake interface to STAC data catalogs'

  description: |
    This is an intake data source for STAC catalogs. The SpatioTemporal Asset
    Catalog (STAC) specification provides a common language to describe a
    range of geospatial information, so it can more easily be indexed and
    discovered. A 'spatiotemporal asset' is any file that represents
    information about the earth captured in a certain space and time.
  doc_url: https://intake-stac.readthedocs.io
  dev_url: https://github.com/pangeo-data/intake-stac

extra:
  recipe-maintainers:
    - jhamman
    - matthewhanson
    - ocefpaf
