{% set version = "0.3.0" %}

package:
  name: intake-stac
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/i/intake-stac/intake_stac-{{ version }}.tar.gz
  sha256: 19baf6b6392c9843e1ec988f251e3355d17e389d349d76e1e6ddabf4c0d1cbce

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools-scm
  run:
    - python >=3.6
    - fsspec >=0.8.4
    - intake >=0.5.1
    - intake-xarray >=0.4
    - sat-stac ==0.4.*

test:
  imports:
    - intake_stac
    - intake_stac.catalog
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pangeo-data/intake-stac
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Intake interface to STAC data catalogs

  description: |
    This is an intake data source for STAC catalogs. The SpatioTemporal Asset
    Catalog (STAC) specification provides a common language to describe a
    range of geospatial information, so it can more easily be indexed and
    discovered. A 'spatiotemporal asset' is any file that represents
    information about the earth captured in a certain space and time.
  doc_url: https://intake-stac.readthedocs.io
  dev_url: https://github.com/pangeo-data/intake-stac

extra:
  recipe-maintainers:
    - jhamman
    - matthewhanson
    - ocefpaf
    - scottyhq
